#!/bin/bash

setup_python() {
  proxy
  if command -v pyenv > /dev/null 2>&1; then
    success "pyenv 已安装"
  else
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$HOME/.pyenv/bin:$PATH"
    eval "$(pyenv init -)"
    if command -v pyenv > /dev/null 2>&1; then
      success "pyenv 已安装"
    else
      warning "pyenv 未安装"
      if confirm "是否安装 pyenv?"; then
        curl https://pyenv.run | bash || error "pyenv 安装失败"
        success "pyenv 已经安装"
        export PYENV_ROOT="$HOME/.pyenv"
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init -)"
      fi
    fi
  fi
  pyenv shell 3.12 || pyenv install 3.12 && pyenv rehash && pyenv shell 3.12
  unproxy
  python -m venv --copies "${COMFYUI_INSTALL_DIR}/.venv"
}
