#!/bin/bash

setup_service() {
  info "配置系统服务..."
  info "创建服务..."
  remove_service
  sudo echo "$COMFYUI_SERVICE" | sudo tee /etc/systemd/system/comfyui.service
  systemctl daemon-reload
  if [ -e /etc/systemd/system/comfyui ]; then
    sudo systemctl enable comfyui
    start_service
  fi
}

start_service() {
  systemctl daemon-reload
  if [ -e /etc/systemd/system/comfyui ]; then
    sudo systemctl start comfyui
    success "服务启动成功"
  fi
}

stop_service() {
  systemctl daemon-reload
  if [ -e /etc/systemd/system/comfyui ]; then
    sudo systemctl stop comfyui
    success "服务停止成功"
  fi
}

restart_service() {
  systemctl daemon-reload
  if [ -e /etc/systemd/system/comfyui ]; then
    sudo systemctl restart comfyui
    success "服务重启成功"
  fi
}