#!/bin/bash

setup_node() {
  if ! command -v nvm &> /dev/null; then
    export NVM_DIR="$HOME/.nvm"
    if [ -s "$NVM_DIR/nvm.sh" ]; then
      # 在当前shell加载nvm（避免使用子shell）
      \. "$NVM_DIR/nvm.sh"  # 加载nvm核心功能

      # 加载自动补全（如果存在）
      if [ -s "$NVM_DIR/bash_completion" ]; then
        \. "$NVM_DIR/bash_completion"
      fi
    else
      proxy
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh | bash
      unproxy
      # 在当前shell加载nvm（避免使用子shell）
      \. "$NVM_DIR/nvm.sh"  # 加载nvm核心功能

      # 加载自动补全（如果存在）
      if [ -s "$NVM_DIR/bash_completion" ]; then
        \. "$NVM_DIR/bash_completion"
      fi    
    fi
  fi

  if ! command -v node &> /dev/null; then
      info "安装 node.js ${NODE_VERSION} LTS"
      nvm install ${NODE_VERSION}
  fi
  success "Node.js 版本："
  node --version
  success "npm 版本："
  npm --version
  npm config set registry https://registry.npmmirror.com/
}